import type { Profile, Role, Candidate, StageHistory, ActivityLog, JobPosting, Referral } from '@/types';

export const MOCK_MODE = process.env.NEXT_PUBLIC_MOCK_MODE === 'true';

// ── Profiles ──────────────────────────────────────────────────────────────────

export const mockProfiles: Profile[] = [
  {
    id: 'profile-admin-1',
    email: 'admin@hirestudio.com',
    full_name: 'Alex Rivera',
    role: 'recruitment_admin',
    created_at: '2025-01-10T09:00:00Z',
  },
  {
    id: 'profile-hor-1',
    email: 'head@hirestudio.com',
    full_name: 'Jordan Lee',
    role: 'head_of_recruitment',
    created_at: '2025-01-10T09:00:00Z',
  },
  {
    id: 'profile-rec-1',
    email: 'sarah@hirestudio.com',
    full_name: 'Sarah Tan',
    role: 'recruiter',
    created_at: '2025-02-01T09:00:00Z',
  },
  {
    id: 'profile-rec-2',
    email: 'marcus@hirestudio.com',
    full_name: 'Marcus Dela Cruz',
    role: 'recruiter',
    created_at: '2025-02-15T09:00:00Z',
  },
  {
    id: 'profile-src-1',
    email: 'dana@hirestudio.com',
    full_name: 'Dana Okonkwo',
    role: 'sourcer',
    created_at: '2025-03-01T09:00:00Z',
  },
];

export const mockAdminProfile = mockProfiles[0];

// ── Roles ─────────────────────────────────────────────────────────────────────

export const mockRoles: Role[] = [
  {
    id: 'role-1',
    title: 'Senior React Developer',
    role_type: 'Active',
    headcount: 2,
    client_name: 'TechCorp USA',
    account_manager: 'Jamie Brooks',
    client_monthly_rate: 8500,
    estimated_budget_pay_rate: 5500,
    timezone: 'US/Eastern',
    target_onboarding_date: '2026-05-01',
    target_regions: ['Philippines', 'Latin America'],
    jd_link: 'https://example.com/jd/react-dev',
    salary_min: 4500,
    salary_max: 6000,
    main_recruiter_id: 'profile-rec-1',
    sourcer_id: 'profile-src-1',
    internal_notes: 'Client prefers someone with fintech background. Must have TypeScript.',
    status: 'open',
    date_opened: '2026-03-10',
    created_at: '2026-03-10T08:00:00Z',
    updated_at: '2026-03-28T14:20:00Z',
    main_recruiter: mockProfiles[2],
    sourcer: mockProfiles[4],
  },
  {
    id: 'role-2',
    title: 'Product Manager – FinTech',
    role_type: 'Active',
    headcount: 1,
    client_name: 'Meridian Capital',
    account_manager: 'Casey Walsh',
    client_monthly_rate: 11000,
    estimated_budget_pay_rate: 7500,
    timezone: 'US/Central',
    target_regions: ['Latin America', 'South Africa'],
    salary_min: 6000,
    salary_max: 8000,
    main_recruiter_id: 'profile-rec-2',
    sourcer_id: 'profile-src-1',
    status: 'open',
    date_opened: '2026-03-05',
    created_at: '2026-03-05T09:00:00Z',
    updated_at: '2026-03-29T11:00:00Z',
    main_recruiter: mockProfiles[3],
    sourcer: mockProfiles[4],
  },
  {
    id: 'role-3',
    title: 'DevOps Engineer',
    role_type: 'Replacement',
    headcount: 1,
    client_name: 'CloudScale Ltd',
    account_manager: 'Jamie Brooks',
    client_monthly_rate: 9200,
    estimated_budget_pay_rate: 6000,
    timezone: 'US/Pacific',
    target_regions: ['Philippines', 'Nigeria'],
    salary_min: 5000,
    salary_max: 6500,
    main_recruiter_id: 'profile-rec-1',
    status: 'open',
    date_opened: '2026-03-20',
    created_at: '2026-03-20T09:00:00Z',
    updated_at: '2026-03-30T09:00:00Z',
    main_recruiter: mockProfiles[2],
  },
  {
    id: 'role-4',
    title: 'Data Analyst',
    role_type: 'Inquiry',
    headcount: 3,
    client_name: 'Insight Analytics',
    account_manager: 'Taylor Nguyen',
    client_monthly_rate: 5500,
    estimated_budget_pay_rate: 3500,
    timezone: 'AU/Sydney',
    target_regions: ['Philippines', 'Sri Lanka'],
    salary_min: 2800,
    salary_max: 3800,
    main_recruiter_id: 'profile-rec-2',
    status: 'open',
    date_opened: '2026-03-25',
    created_at: '2026-03-25T09:00:00Z',
    updated_at: '2026-03-31T08:00:00Z',
    main_recruiter: mockProfiles[3],
  },
  {
    id: 'role-5',
    title: 'Executive Assistant',
    role_type: 'Internal',
    headcount: 1,
    client_name: 'HireStudio Internal',
    account_manager: '',
    client_monthly_rate: 3200,
    timezone: 'US/Eastern',
    target_regions: ['Philippines'],
    salary_min: 1800,
    salary_max: 2400,
    main_recruiter_id: 'profile-rec-1',
    status: 'paused',
    date_opened: '2026-02-15',
    created_at: '2026-02-15T09:00:00Z',
    updated_at: '2026-03-01T09:00:00Z',
    main_recruiter: mockProfiles[2],
  },
  {
    id: 'role-6',
    title: 'UI/UX Designer',
    role_type: 'Active',
    headcount: 1,
    client_name: 'PixelForge Studio',
    account_manager: 'Casey Walsh',
    client_monthly_rate: 6500,
    estimated_budget_pay_rate: 4200,
    timezone: 'EU/London',
    target_regions: ['Nigeria', 'South Africa'],
    salary_min: 3500,
    salary_max: 4500,
    main_recruiter_id: 'profile-rec-2',
    sourcer_id: 'profile-src-1',
    status: 'closed',
    date_opened: '2026-01-10',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-03-22T15:30:00Z',
    main_recruiter: mockProfiles[3],
    sourcer: mockProfiles[4],
  },
];

// ── Stage History ─────────────────────────────────────────────────────────────

export const mockStageHistory: StageHistory[] = [
  { id: 'sh-1', candidate_id: 'cand-1', to_stage: 'applied', created_at: '2026-03-11T10:00:00Z', changed_by_id: 'profile-rec-1', changed_by: mockProfiles[2] },
  { id: 'sh-2', candidate_id: 'cand-1', from_stage: 'applied', to_stage: 'screening', created_at: '2026-03-13T11:00:00Z', changed_by_id: 'profile-rec-1', changed_by: mockProfiles[2] },
  { id: 'sh-3', candidate_id: 'cand-1', from_stage: 'screening', to_stage: 'interview_1', created_at: '2026-03-18T09:30:00Z', changed_by_id: 'profile-rec-1', changed_by: mockProfiles[2] },
  { id: 'sh-4', candidate_id: 'cand-1', from_stage: 'interview_1', to_stage: 'interview_2', created_at: '2026-03-25T14:00:00Z', changed_by_id: 'profile-hor-1', changed_by: mockProfiles[1], notes: 'Strong technical performance. Moving to client round.' },

  { id: 'sh-5', candidate_id: 'cand-2', to_stage: 'applied', created_at: '2026-03-12T09:00:00Z', changed_by_id: 'profile-rec-2', changed_by: mockProfiles[3] },
  { id: 'sh-6', candidate_id: 'cand-2', from_stage: 'applied', to_stage: 'screening', created_at: '2026-03-14T10:00:00Z', changed_by_id: 'profile-rec-2', changed_by: mockProfiles[3] },
  { id: 'sh-7', candidate_id: 'cand-2', from_stage: 'screening', to_stage: 'offer', created_at: '2026-03-28T10:00:00Z', changed_by_id: 'profile-rec-2', changed_by: mockProfiles[3], notes: 'Client loved the candidate. Offer extended.' },

  { id: 'sh-8', candidate_id: 'cand-3', to_stage: 'applied', created_at: '2026-03-15T09:00:00Z', changed_by_id: 'profile-rec-1', changed_by: mockProfiles[2] },
  { id: 'sh-9', candidate_id: 'cand-3', from_stage: 'applied', to_stage: 'rejected', created_at: '2026-03-17T11:00:00Z', changed_by_id: 'profile-rec-1', changed_by: mockProfiles[2], notes: 'Salary expectation too high.' },

  { id: 'sh-10', candidate_id: 'cand-4', to_stage: 'applied', created_at: '2026-03-20T09:00:00Z', changed_by_id: 'profile-rec-2', changed_by: mockProfiles[3] },
  { id: 'sh-11', candidate_id: 'cand-4', from_stage: 'applied', to_stage: 'screening', created_at: '2026-03-22T10:00:00Z', changed_by_id: 'profile-rec-2', changed_by: mockProfiles[3] },

  { id: 'sh-12', candidate_id: 'cand-5', to_stage: 'applied', created_at: '2026-03-22T09:00:00Z', changed_by_id: 'profile-rec-1', changed_by: mockProfiles[2] },
  { id: 'sh-13', candidate_id: 'cand-5', from_stage: 'applied', to_stage: 'screening', created_at: '2026-03-24T10:00:00Z', changed_by_id: 'profile-rec-1', changed_by: mockProfiles[2] },
  { id: 'sh-14', candidate_id: 'cand-5', from_stage: 'screening', to_stage: 'interview_1', created_at: '2026-03-28T11:00:00Z', changed_by_id: 'profile-rec-1', changed_by: mockProfiles[2] },

  { id: 'sh-15', candidate_id: 'cand-6', to_stage: 'applied', created_at: '2026-03-05T09:00:00Z', changed_by_id: 'profile-rec-2', changed_by: mockProfiles[3] },
  { id: 'sh-16', candidate_id: 'cand-6', from_stage: 'applied', to_stage: 'screening', created_at: '2026-03-07T10:00:00Z', changed_by_id: 'profile-rec-2', changed_by: mockProfiles[3] },
  { id: 'sh-17', candidate_id: 'cand-6', from_stage: 'screening', to_stage: 'interview_1', created_at: '2026-03-12T09:00:00Z', changed_by_id: 'profile-rec-2', changed_by: mockProfiles[3] },
  { id: 'sh-18', candidate_id: 'cand-6', from_stage: 'interview_1', to_stage: 'hired', created_at: '2026-03-20T14:00:00Z', changed_by_id: 'profile-hor-1', changed_by: mockProfiles[1], notes: 'Hired! Starting April 14.' },
];

// ── Candidates ────────────────────────────────────────────────────────────────

export const mockCandidates: Candidate[] = [
  {
    id: 'cand-1',
    name: 'Miguel Santos',
    email: 'miguel.santos@email.com',
    whatsapp: '+63 917 555 1234',
    role_id: 'role-1',
    endorsement_writeup: 'Miguel is a strong React developer with 6 years of experience in fintech. Excellent communication and strong TypeScript skills.',
    resume_url: 'https://example.com/resumes/miguel-santos.pdf',
    loom_video_link: 'https://loom.com/share/placeholder-miguel',
    salary_expectation_min: 4800,
    salary_expectation_max: 5500,
    availability: 'ASAP',
    working_timezone: 'Asia/Manila',
    reason_for_leaving: 'Current company is downsizing the dev team.',
    references: [
      { name: 'Ben Reyes', email: 'ben@example.com', phone: '+63 917 000 0001', relationship: 'Direct Manager', status: 'pending' },
      { name: 'Clara Lim', email: 'clara@example.com', phone: '+63 917 000 0002', relationship: 'Team Lead', status: 'pending' },
    ],
    endorsement_stage: 'interview_2',
    recruiter_id: 'profile-rec-1',
    assigned_reviewer_id: 'profile-hor-1',
    created_at: '2026-03-11T10:00:00Z',
    updated_at: '2026-03-25T14:00:00Z',
    role: mockRoles[0],
    recruiter: mockProfiles[2],
    assigned_reviewer: mockProfiles[1],
    stage_history: mockStageHistory.filter(s => s.candidate_id === 'cand-1'),
  },
  {
    id: 'cand-2',
    name: 'Valentina Cruz',
    email: 'v.cruz@email.com',
    whatsapp: '+52 55 5555 6789',
    role_id: 'role-2',
    endorsement_writeup: 'Valentina has 8 years of product experience with 3 at a leading LATAM fintech. Exceptional stakeholder management.',
    resume_url: 'https://example.com/resumes/valentina-cruz.pdf',
    loom_video_link: 'https://loom.com/share/placeholder-valentina',
    salary_expectation_min: 7000,
    salary_expectation_max: 7500,
    availability: '2 Weeks',
    working_timezone: 'America/Mexico_City',
    reason_for_leaving: 'Looking for a remote-first company with global exposure.',
    references: [
      { name: 'Roberto Mora', email: 'roberto@example.com', phone: '+52 55 1234 5678', relationship: 'CEO', status: 'completed' },
    ],
    endorsement_stage: 'offer',
    recruiter_id: 'profile-rec-2',
    assigned_reviewer_id: 'profile-hor-1',
    created_at: '2026-03-12T09:00:00Z',
    updated_at: '2026-03-28T10:00:00Z',
    role: mockRoles[1],
    recruiter: mockProfiles[3],
    assigned_reviewer: mockProfiles[1],
    stage_history: mockStageHistory.filter(s => s.candidate_id === 'cand-2'),
  },
  {
    id: 'cand-3',
    name: 'Kwame Asante',
    email: 'kwame.asante@email.com',
    whatsapp: '+234 801 555 9876',
    role_id: 'role-1',
    endorsement_writeup: 'Solid React background, but salary expectations are significantly above budget.',
    resume_url: 'https://example.com/resumes/kwame-asante.pdf',
    salary_expectation_min: 7500,
    salary_expectation_max: 9000,
    availability: '1 Month',
    working_timezone: 'Africa/Lagos',
    red_flags: 'Salary expectation too high for the role budget.',
    references: [],
    endorsement_stage: 'rejected',
    recruiter_id: 'profile-rec-1',
    created_at: '2026-03-15T09:00:00Z',
    updated_at: '2026-03-17T11:00:00Z',
    role: mockRoles[0],
    recruiter: mockProfiles[2],
    stage_history: mockStageHistory.filter(s => s.candidate_id === 'cand-3'),
  },
  {
    id: 'cand-4',
    name: 'Priya Nair',
    email: 'priya.nair@email.com',
    whatsapp: '+94 77 555 4321',
    role_id: 'role-4',
    endorsement_writeup: 'Priya has strong SQL and Python skills with 4 years in analytics. Great communication.',
    resume_url: 'https://example.com/resumes/priya-nair.pdf',
    salary_expectation_min: 3000,
    salary_expectation_max: 3500,
    availability: 'ASAP',
    working_timezone: 'Asia/Colombo',
    references: [],
    endorsement_stage: 'screening',
    recruiter_id: 'profile-rec-2',
    created_at: '2026-03-20T09:00:00Z',
    updated_at: '2026-03-22T10:00:00Z',
    role: mockRoles[3],
    recruiter: mockProfiles[3],
    stage_history: mockStageHistory.filter(s => s.candidate_id === 'cand-4'),
  },
  {
    id: 'cand-5',
    name: 'Carlo Mendoza',
    email: 'carlo.mendoza@email.com',
    whatsapp: '+63 906 555 7788',
    role_id: 'role-3',
    endorsement_writeup: 'Carlo is a hands-on DevOps engineer with Kubernetes and AWS expertise. 5 years experience.',
    resume_url: 'https://example.com/resumes/carlo-mendoza.pdf',
    loom_video_link: 'https://loom.com/share/placeholder-carlo',
    salary_expectation_min: 5200,
    salary_expectation_max: 6000,
    availability: '1 Week',
    working_timezone: 'Asia/Manila',
    references: [],
    endorsement_stage: 'interview_1',
    recruiter_id: 'profile-rec-1',
    assigned_reviewer_id: 'profile-hor-1',
    created_at: '2026-03-22T09:00:00Z',
    updated_at: '2026-03-28T11:00:00Z',
    role: mockRoles[2],
    recruiter: mockProfiles[2],
    assigned_reviewer: mockProfiles[1],
    stage_history: mockStageHistory.filter(s => s.candidate_id === 'cand-5'),
  },
  {
    id: 'cand-6',
    name: 'Aisha Obi',
    email: 'aisha.obi@email.com',
    whatsapp: '+27 82 555 3344',
    role_id: 'role-6',
    endorsement_writeup: 'Aisha is an exceptional UI/UX designer with a portfolio focused on SaaS dashboards. 6 years experience.',
    resume_url: 'https://example.com/resumes/aisha-obi.pdf',
    portfolio_url: 'https://aishadesigns.co.za',
    salary_expectation_min: 4000,
    salary_expectation_max: 4200,
    availability: 'ASAP',
    working_timezone: 'Africa/Johannesburg',
    references: [
      { name: 'Greg Steyn', email: 'greg@example.com', phone: '+27 82 000 0001', relationship: 'Previous Client', status: 'completed' },
    ],
    endorsement_stage: 'hired',
    recruiter_id: 'profile-rec-2',
    created_at: '2026-03-05T09:00:00Z',
    updated_at: '2026-03-20T14:00:00Z',
    role: mockRoles[5],
    recruiter: mockProfiles[3],
    stage_history: mockStageHistory.filter(s => s.candidate_id === 'cand-6'),
  },
];

// ── Activity Log ──────────────────────────────────────────────────────────────

export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log-1',
    role_id: 'role-1',
    user_id: 'profile-rec-1',
    action: 'Role created via Slack /role command',
    created_at: '2026-03-10T08:00:00Z',
    user: mockProfiles[2],
    role: { id: 'role-1', title: 'Senior React Developer', client_name: 'TechCorp USA', status: 'open' },
  },
  {
    id: 'log-2',
    candidate_id: 'cand-1',
    role_id: 'role-1',
    user_id: 'profile-rec-1',
    action: 'Candidate endorsed',
    new_value: 'Miguel Santos',
    created_at: '2026-03-11T10:00:00Z',
    user: mockProfiles[2],
    candidate: { name: 'Miguel Santos' },
    role: { id: 'role-1', title: 'Senior React Developer', client_name: 'TechCorp USA', status: 'open' },
  },
  {
    id: 'log-3',
    candidate_id: 'cand-1',
    role_id: 'role-1',
    user_id: 'profile-rec-1',
    action: 'Stage moved',
    field_changed: 'endorsement_stage',
    old_value: 'applied',
    new_value: 'screening',
    created_at: '2026-03-13T11:00:00Z',
    user: mockProfiles[2],
    candidate: { name: 'Miguel Santos' },
    role: { id: 'role-1', title: 'Senior React Developer', client_name: 'TechCorp USA', status: 'open' },
  },
  {
    id: 'log-4',
    role_id: 'role-2',
    user_id: 'profile-rec-2',
    action: 'Role created',
    created_at: '2026-03-05T09:00:00Z',
    user: mockProfiles[3],
    role: { id: 'role-2', title: 'Product Manager – FinTech', client_name: 'Meridian Capital', status: 'open' },
  },
  {
    id: 'log-5',
    candidate_id: 'cand-2',
    role_id: 'role-2',
    user_id: 'profile-rec-2',
    action: 'Stage moved',
    field_changed: 'endorsement_stage',
    old_value: 'screening',
    new_value: 'offer',
    created_at: '2026-03-28T10:00:00Z',
    user: mockProfiles[3],
    candidate: { name: 'Valentina Cruz' },
    role: { id: 'role-2', title: 'Product Manager – FinTech', client_name: 'Meridian Capital', status: 'open' },
  },
  {
    id: 'log-6',
    role_id: 'role-1',
    user_id: 'profile-admin-1',
    action: 'Role updated',
    field_changed: 'status',
    old_value: 'open',
    new_value: 'open',
    created_at: '2026-03-28T14:20:00Z',
    user: mockProfiles[0],
    role: { id: 'role-1', title: 'Senior React Developer', client_name: 'TechCorp USA', status: 'open' },
  },
  {
    id: 'log-7',
    candidate_id: 'cand-6',
    role_id: 'role-6',
    user_id: 'profile-hor-1',
    action: 'Stage moved',
    field_changed: 'endorsement_stage',
    old_value: 'interview_1',
    new_value: 'hired',
    created_at: '2026-03-20T14:00:00Z',
    user: mockProfiles[1],
    candidate: { name: 'Aisha Obi' },
    role: { id: 'role-6', title: 'UI/UX Designer', client_name: 'PixelForge Studio', status: 'closed' },
  },
  {
    id: 'log-8',
    candidate_id: 'cand-5',
    role_id: 'role-3',
    user_id: 'profile-rec-1',
    action: 'Stage moved',
    field_changed: 'endorsement_stage',
    old_value: 'screening',
    new_value: 'interview_1',
    created_at: '2026-03-28T11:00:00Z',
    user: mockProfiles[2],
    candidate: { name: 'Carlo Mendoza' },
    role: { id: 'role-3', title: 'DevOps Engineer', client_name: 'CloudScale Ltd', status: 'open' },
  },
];

// ── Job Postings ──────────────────────────────────────────────────────────────

export const mockJobPostings: JobPosting[] = [
  {
    id: 'post-1',
    role_id: 'role-1',
    platform_name: 'LinkedIn',
    date_posted: '2026-03-10',
    sponsored: true,
    duration_days: 30,
    ad_spend: 450,
    application_count: 67,
    source_breakdown: { 'Direct Apply': 40, 'Easy Apply': 27 },
    created_at: '2026-03-10T09:00:00Z',
    updated_at: '2026-03-31T09:00:00Z',
    role: mockRoles[0],
  },
  {
    id: 'post-2',
    role_id: 'role-1',
    platform_name: 'Indeed',
    date_posted: '2026-03-11',
    sponsored: true,
    duration_days: 30,
    ad_spend: 280,
    application_count: 42,
    source_breakdown: { Organic: 18, Sponsored: 24 },
    created_at: '2026-03-11T09:00:00Z',
    updated_at: '2026-03-31T09:00:00Z',
    role: mockRoles[0],
  },
  {
    id: 'post-3',
    role_id: 'role-2',
    platform_name: 'LinkedIn',
    date_posted: '2026-03-06',
    sponsored: false,
    duration_days: 21,
    ad_spend: 0,
    application_count: 18,
    source_breakdown: { 'Direct Apply': 18 },
    created_at: '2026-03-06T09:00:00Z',
    updated_at: '2026-03-31T09:00:00Z',
    role: mockRoles[1],
  },
  {
    id: 'post-4',
    role_id: 'role-3',
    platform_name: 'JobStreet',
    date_posted: '2026-03-21',
    sponsored: true,
    duration_days: 14,
    ad_spend: 180,
    application_count: 31,
    source_breakdown: { Organic: 12, Featured: 19 },
    created_at: '2026-03-21T09:00:00Z',
    updated_at: '2026-03-31T09:00:00Z',
    role: mockRoles[2],
  },
  {
    id: 'post-5',
    role_id: 'role-4',
    platform_name: 'LinkedIn',
    date_posted: '2026-03-26',
    sponsored: false,
    duration_days: 30,
    ad_spend: 0,
    application_count: 9,
    source_breakdown: { 'Direct Apply': 9 },
    created_at: '2026-03-26T09:00:00Z',
    updated_at: '2026-03-31T09:00:00Z',
    role: mockRoles[3],
  },
  {
    id: 'post-6',
    role_id: 'role-6',
    platform_name: 'Dribbble',
    date_posted: '2026-01-12',
    sponsored: true,
    duration_days: 30,
    ad_spend: 320,
    application_count: 55,
    source_breakdown: { Organic: 20, Sponsored: 35 },
    created_at: '2026-01-12T09:00:00Z',
    updated_at: '2026-02-11T09:00:00Z',
    role: mockRoles[5],
  },
];

// ── Referrals ─────────────────────────────────────────────────────────────────

export const mockReferrals: Referral[] = [
  {
    id: 'ref-1',
    contractor_name: 'Jess Villanueva',
    referral_name: 'Patrick Gomez',
    resume_link: 'https://example.com/resumes/patrick-gomez.pdf',
    video_intro_link: 'https://loom.com/share/ref-patrick',
    whatsapp_number: '+63 917 555 8800',
    role_applying_for: 'Senior React Developer',
    submission_date: '2026-03-15',
    status: 'reviewing',
    bonus_eligible: true,
    bonus_paid: false,
    notes: 'Patrick worked with Jess at their previous company.',
    created_at: '2026-03-15T10:00:00Z',
    updated_at: '2026-03-16T09:00:00Z',
  },
  {
    id: 'ref-2',
    contractor_name: 'Ana Reyes',
    referral_name: 'Luis Castillo',
    resume_link: 'https://example.com/resumes/luis-castillo.pdf',
    whatsapp_number: '+52 55 5555 2211',
    role_applying_for: 'Product Manager – FinTech',
    submission_date: '2026-03-18',
    status: 'shortlisted',
    bonus_eligible: true,
    bonus_paid: false,
    created_at: '2026-03-18T11:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 'ref-3',
    contractor_name: 'Tunde Adeyemi',
    referral_name: 'Chidi Eze',
    resume_link: 'https://example.com/resumes/chidi-eze.pdf',
    video_intro_link: 'https://loom.com/share/ref-chidi',
    whatsapp_number: '+234 803 555 4455',
    role_applying_for: 'DevOps Engineer',
    submission_date: '2026-03-22',
    status: 'pending',
    bonus_eligible: false,
    bonus_paid: false,
    created_at: '2026-03-22T09:00:00Z',
    updated_at: '2026-03-22T09:00:00Z',
  },
  {
    id: 'ref-4',
    contractor_name: 'Maria Santos',
    referral_name: 'Elena Reyes',
    resume_link: 'https://example.com/resumes/elena-reyes.pdf',
    whatsapp_number: '+63 906 555 1122',
    role_applying_for: 'Data Analyst',
    submission_date: '2026-03-28',
    status: 'hired',
    bonus_eligible: true,
    bonus_paid: true,
    notes: 'Bonus of $500 paid on 2026-03-30.',
    created_at: '2026-03-28T10:00:00Z',
    updated_at: '2026-03-30T14:00:00Z',
  },
];
